apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green-deployment
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-deployment
      version: v1
  template:
    metadata:
      labels:
        app: green-deployment
        version: v1
    spec:
      containers:
      - name: green-deployment
        image: green_service:v1
        ports:
        - containerPort: 8081
