apiVersion: apps/v2
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green-deployment
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-deployment
      version: v2
  template:
    metadata:
      labels:
        app: green-deployment
        version: v2
    spec:
      containers:
      - name: green-deployment
        image: green_service:v2
        ports:
        - containerPort: 8081
