apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: virtual-service
  namespace: networking
spec:
  hosts:
    - "*"               
  gateways:
    - api-gateway   
       
  http:
    #<< ==== blue service routes ==== >>#
    - match:
        - uri:
            prefix: "/blue" 
      rewrite:
        uri: "/"
      route:
        #<< ==== traffic splitting deployment A ==== >>#
        - destination:
            host: blue-service.default.svc.cluster.local
            subset: v1
            port:
              number: 9000
          weight: 50
          #<< ==== traffic splitting deployment B ==== >>#
        - destination:
            host: blue-service.default.svc.cluster.local
            subset: v2
            port:
              number: 9000
          weight: 50

    #<< ==== green service routes ==== >>#
    - match: 
        - uri:
            prefix: "/green"
      rewrite:
        uri: "/" 
      route:
        #<< ==== traffic splitting deployment A ==== >>#
        - destination:
            host: green-service.default.svc.cluster.local
            subset: v1
            port:
              number: 9001
          weight: 70
        #<< ==== traffic splitting deployment B ==== >>#
        - destination:   
            host: green-service.default.svc.cluster.local
            subset: v2
            port:
              number: 9001
          weight: 30

    #<< ==== red service routes ==== >>#
    - match:
        - uri: 
            prefix: "/red"  
      rewrite:
        uri: "/"
      route:
      #<< ==== traffic splitting deployment A ==== >>#
        - destination:
            host: red-service.default.svc.cluster.local
            subset: v1
            port:
              number: 9002
          weight: 90
      #<< ==== traffic splitting deployment B ==== >># 
        - destination:
            host: red-service.default.svc.cluster.local   
            subset: v2
            port:   
              number: 9002    
          weight: 10
