apiVersion: apps/v2
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    app: blue-deployment
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-deployment
      version: v2
  template:
    metadata:
      labels:
        app: blue-deployment
        version: v2
    spec:
      containers:
      - name: blue-deployment
        image: blue_service:v2
        ports:
        - containerPort: 8080
