apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment-a
  labels:
    app: blue-deployment
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-deployment
      version: v1
  template:
    metadata:
      labels:
        app: blue-deployment
        version: v1
    spec:
      containers:
      - name: blue-deployment
        image: blue_service:v1
        ports:
        - containerPort: 8080
