apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: deployment
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment
      version: v1
  template:
    metadata:
      labels:
        app: deployment
        version: v1
    spec:
      containers:
      - name: deployment
        image: canary_demo_apps:v1
        ports:
        - containerPort: 8080
