apiVersion: apps/v2
kind: Deployment
metadata:
  name: red-deployment
  labels:
    app: red-deployment
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: red-deployment
      version: v2
  template:
    metadata:
      labels:
        app: red-deployment
        version: v2
    spec:
      containers:
      - name: red-deployment
        image: red_service:v2
        ports:
        - containerPort: 8080
