apiVersion: apps/v1
kind: Deployment
metadata:
  name: red-deployment
  labels:
    app: red-deployment
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: red-deployment
      version: v1
  template:
    metadata:
      labels:
        app: red-deployment
        version: v1
    spec:
      containers:
      - name: red-deployment
        image: red_service:v1
        ports:
        - containerPort: 8082
